### ISSUE TITLE
Server.cfg/autoexec.cfg

### ISSUE THREAD

**Issue by gerrard9099** [BatMen/csgo-retakes-splewis-convar-weapon-allocator#11]
Only pistol rounds throughot 30 rounds. pistolrounds value is 5, dosen't react to it.

**Comment by gerrard9099** [comment]
Fixed.

**Comment by DarrenStahl** [comment]
I also have this issue, what is the workaround?

**Comment by BatMen** [comment]
You should put : 
- sm_retakes_weapon_primary_enabled 1 (if 0, only pistol rounds)
- sm_retakes_weapon_pistolrounds 5

Is this ok?

**Comment by DarrenStahl** [comment]
Still does not work. The only way I have found to get primary weapons is by setting
* sm_retakes_weapon_pistolrounds 0

**Comment by BatMen** [comment]
Do you test it alone on a server? Because rounds are not considered played when alone on a server. You have to be 2 at least.

**Comment by DarrenStahl** [comment]
Ah, ok. That would be it.

**Comment by BatMen** [comment]
I think of it because you were fast to respond :)
Please come back if you've got problem. I keep it opened.

**Comment by gerrard9099** [comment]
Yes, i fixed it by playing with 2 or more players, only tried it by myself at first.
